// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowParallel.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("N11SingleScenario")]
    public partial class N11SingleScenarioFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "N11SingleScenario.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "N11SingleScenario", "\tThis feature will test functionality of loging in, searching a product from prod" +
                    "uct seaching page after than adding and deleting that product to the User basket" +
                    " from HomePage", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1.Navigate to site\'s HomePage 2.Successful login with Valid Credential 3.Product " +
            "searching with query 4.Navigate through search result page by pagination 5.Addin" +
            "g product from above to favorites 6.Deleting the product from favorites list")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        [NUnit.Framework.TestCaseAttribute("\'http://www.n11.com/\'", "\'n11.com - Alışverişin Uğurlu Adresi\'", "\'https://www.n11.com/\'", "\'parallel\'", "\'chrome\'", "\'berktoprakci@gmail.com\'", "\'Test1ngpass\'", "\'Berk Toprakçı\'", "\'samsung\'", "\'2\'", "\'3\'", null)]
        [NUnit.Framework.TestCaseAttribute("\'http://www.n11.com/\'", "\'n11.com - Alışverişin Uğurlu Adresi\'", "\'https://www.n11.com/\'", "\'parallel\'", "\'firefox\'", "\'berktoprakci@gmail.com\'", "\'Test1ngpass\'", "\'Berk Toprakçı\'", "\'samsung\'", "\'2\'", "\'3\'", null)]
        [NUnit.Framework.TestCaseAttribute("\'http://www.n11.com/\'", "\'n11.com - Alışverişin Uğurlu Adresi\'", "\'https://www.n11.com/\'", "\'parallel\'", "\'ie\'", "\'berktoprakci@gmail.com\'", "\'Test1ngpass\'", "\'Berk Toprakçı\'", "\'samsung\'", "\'2\'", "\'3\'", null)]
        [NUnit.Framework.TestCaseAttribute("\'http://www.n11.com/\'", "\'n11.com - Alışverişin Uğurlu Adresi\'", "\'https://www.n11.com/\'", "\'parallel\'", "\'safari\'", "\'berktoprakci@gmail.com\'", "\'Test1ngpass\'", "\'Berk Toprakçı\'", "\'samsung\'", "\'2\'", "\'3\'", null)]
        public virtual void _1_NavigateToSitesHomePage2_SuccessfulLoginWithValidCredential3_ProductSearchingWithQuery4_NavigateThroughSearchResultPageByPagination5_AddingProductFromAboveToFavorites6_DeletingTheProductFromFavoritesList(string siteaddress, string pagetitle, string siteurl, string profile, string environment, string username, string password, string fullname, string productname, string pagenumber, string queuenumber, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1.Navigate to site\'s HomePage 2.Successful login with Valid Credential 3.Product " +
                    "searching with query 4.Navigate through search result page by pagination 5.Addin" +
                    "g product from above to favorites 6.Deleting the product from favorites list", null, @__tags);
#line 5
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
 testRunner.And(string.Format("User {0} at {1} browser home page", profile, environment), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 7
 testRunner.And(string.Format("User navigate to {0}", siteaddress), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 8
 testRunner.And(string.Format("Page title and landed url should {0} and {1}", pagetitle, siteurl), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 9
 testRunner.And("User at  Homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 10
 testRunner.And("User Navigating to LogIn Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 11
 testRunner.And(string.Format("User enter {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 12
 testRunner.And("Click on the LogIn button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 13
 testRunner.And(string.Format("User {0} should be visible under my account section", fullname), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 14
 testRunner.And("User at Homepage after Successful login", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 15
 testRunner.And(string.Format("User Typing {0} to searchbar", productname), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 16
 testRunner.And("Clicking to the search button in order to search for that product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 17
 testRunner.And(string.Format("User should see the search results with {0}", productname), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 18
 testRunner.And("User is on the first page of searching results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 19
 testRunner.And(string.Format("User is selecting {0} from pagination", pagenumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 20
 testRunner.And(string.Format("User should see the {0} th search page results", pagenumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 21
 testRunner.And("User is on the nth page of searching results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 22
 testRunner.And(string.Format("User adding the {0} th product from above to favorites list", queuenumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 23
 testRunner.And("User navigating to their favorites list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 24
 testRunner.And("User should see the added product in their list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 25
 testRunner.And("User is at their favorites list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 26
 testRunner.And("User deletes a product in that list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 27
 testRunner.And("User should not see the deleted product in list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
